# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9b10608e1da8cf0a95684e0f895204c9caa1ba70a67fdb7e17b2c9c1614e602186a655c60a6227cfe55af4bf63e99ed7c460af6f7ef751de95326931ec04e1c

test:
  secret_key_base: 8d2ab22ca7e2703ed3a64568b667d7d6dd2f95cc8dea50fc7b746c50fdbafdc6d41827149fd4b9748c8cfb7c5904d2127f491876494ac4d177b4f0f1caf8f733

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
